### ISSUE TITLE
Error in strsplit(response, "&") : non-character argument

### ISSUE THREAD

**Issue by isomorphisms** [geoffjentry/ROAuth#8]
I'm trying to use `ROAuth` on [tumblr's api](https://www.tumblr.com/docs/en/api/v2)

```
Request-token URL:
POST http://www.tumblr.com/oauth/request_token
Authorize URL:
http://www.tumblr.com/oauth/authorize
Access-token URL:
POST http://www.tumblr.com/oauth/access_token
```

Following the directions in cran.r-project.org/web/packages/ROAuth/ROAuth.pdf:

```
> cred$handshake()
Error in strsplit(response, "&") : non-character argument
```

**Comment by isomorphisms** [comment]
```
> for (obj in ls()) { print(paste(obj, class(get(obj)))) }                                  
[1] "accessURL character"
[1] "authURL character"
[1] "ck character"
[1] "cred OAuth"
[1] "obj character"
[1] "reqURL character"
[1] "sk character"
[1] "testURL character"
```

**Comment by geoffjentry** [comment]
It is entirely possible that ROAuth doesn't work out of the box with any particular OAuth based API, I've personally seen it not work with more than one.

I've personally moved to using httr instead of ROAuth and would recommend others do the same, the only reason I still have this package on CRAN is because the CRAN version of twitteR uses it (and that's only the case because I've not had time to finish the current twitteR version)

**Comment by isomorphisms** [comment]
Thanks Geoff, you're right `httr` works much better.
